### ISSUE TITLE
Large numbers could use comma seperators

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/QC#7]
Eg in this page: https://qc.monarchinitiative.org/scigraph.html

it would be nice to say:

Node | 31,185,796 (+218,193)
-- | --

instead of 

Node | 31185796 (+218193)
-- | --

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/QC/commit/b81ef47490e78fe0f9e8b27e097aef46db5c57b4#diff-e024d20d9f53e6cd034b150513cd5661R395 and https://github.com/monarch-initiative/release-utils/commit/74c247ebd546d3ed76cac56c60ce5b8e258f74a2
